/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as OmOsRouteImport } from './routes/om-os'
import { Route as PrivatRengoeringHelsingoerRouteImport } from './routes/privat-rengoering-helsingoer'
import { Route as PrivatRengoeringHornbaekRouteImport } from './routes/privat-rengoering-hornbaek'
import { Route as PrivatRengoeringNordsjaellandRouteImport } from './routes/privat-rengoering-nordsjaelland'
import { Route as RengoeringshjaelpHelsingoerRouteImport } from './routes/rengoeringshjaelp-helsingoer'
import { Route as SaadanFungererDetRouteImport } from './routes/saadan-fungerer-det'
import { Route as YdelserRouteImport } from './routes/ydelser'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOsRoute = OmOsRouteImport.update({
  id: '/om-os',
  path: '/om-os',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatRengoeringHelsingoerRoute =
  PrivatRengoeringHelsingoerRouteImport.update({
    id: '/privat-rengoering-helsingoer',
    path: '/privat-rengoering-helsingoer',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivatRengoeringHornbaekRoute =
  PrivatRengoeringHornbaekRouteImport.update({
    id: '/privat-rengoering-hornbaek',
    path: '/privat-rengoering-hornbaek',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivatRengoeringNordsjaellandRoute =
  PrivatRengoeringNordsjaellandRouteImport.update({
    id: '/privat-rengoering-nordsjaelland',
    path: '/privat-rengoering-nordsjaelland',
    getParentRoute: () => rootRouteImport,
  } as any)
const RengoeringshjaelpHelsingoerRoute =
  RengoeringshjaelpHelsingoerRouteImport.update({
    id: '/rengoeringshjaelp-helsingoer',
    path: '/rengoeringshjaelp-helsingoer',
    getParentRoute: () => rootRouteImport,
  } as any)
const SaadanFungererDetRoute = SaadanFungererDetRouteImport.update({
  id: '/saadan-fungerer-det',
  path: '/saadan-fungerer-det',
  getParentRoute: () => rootRouteImport,
} as any)
const YdelserRoute = YdelserRouteImport.update({
  id: '/ydelser',
  path: '/ydelser',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/om-os': typeof OmOsRoute
  '/privat-rengoering-helsingoer': typeof PrivatRengoeringHelsingoerRoute
  '/privat-rengoering-hornbaek': typeof PrivatRengoeringHornbaekRoute
  '/privat-rengoering-nordsjaelland': typeof PrivatRengoeringNordsjaellandRoute
  '/rengoeringshjaelp-helsingoer': typeof RengoeringshjaelpHelsingoerRoute
  '/saadan-fungerer-det': typeof SaadanFungererDetRoute
  '/ydelser': typeof YdelserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/om-os': typeof OmOsRoute
  '/privat-rengoering-helsingoer': typeof PrivatRengoeringHelsingoerRoute
  '/privat-rengoering-hornbaek': typeof PrivatRengoeringHornbaekRoute
  '/privat-rengoering-nordsjaelland': typeof PrivatRengoeringNordsjaellandRoute
  '/rengoeringshjaelp-helsingoer': typeof RengoeringshjaelpHelsingoerRoute
  '/saadan-fungerer-det': typeof SaadanFungererDetRoute
  '/ydelser': typeof YdelserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/om-os': typeof OmOsRoute
  '/privat-rengoering-helsingoer': typeof PrivatRengoeringHelsingoerRoute
  '/privat-rengoering-hornbaek': typeof PrivatRengoeringHornbaekRoute
  '/privat-rengoering-nordsjaelland': typeof PrivatRengoeringNordsjaellandRoute
  '/rengoeringshjaelp-helsingoer': typeof RengoeringshjaelpHelsingoerRoute
  '/saadan-fungerer-det': typeof SaadanFungererDetRoute
  '/ydelser': typeof YdelserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kontakt'
    | '/om-os'
    | '/privat-rengoering-helsingoer'
    | '/privat-rengoering-hornbaek'
    | '/privat-rengoering-nordsjaelland'
    | '/rengoeringshjaelp-helsingoer'
    | '/saadan-fungerer-det'
    | '/ydelser'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontakt'
    | '/om-os'
    | '/privat-rengoering-helsingoer'
    | '/privat-rengoering-hornbaek'
    | '/privat-rengoering-nordsjaelland'
    | '/rengoeringshjaelp-helsingoer'
    | '/saadan-fungerer-det'
    | '/ydelser'
  id:
    | '__root__'
    | '/'
    | '/kontakt'
    | '/om-os'
    | '/privat-rengoering-helsingoer'
    | '/privat-rengoering-hornbaek'
    | '/privat-rengoering-nordsjaelland'
    | '/rengoeringshjaelp-helsingoer'
    | '/saadan-fungerer-det'
    | '/ydelser'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  OmOsRoute: typeof OmOsRoute
  PrivatRengoeringHelsingoerRoute: typeof PrivatRengoeringHelsingoerRoute
  PrivatRengoeringHornbaekRoute: typeof PrivatRengoeringHornbaekRoute
  PrivatRengoeringNordsjaellandRoute: typeof PrivatRengoeringNordsjaellandRoute
  RengoeringshjaelpHelsingoerRoute: typeof RengoeringshjaelpHelsingoerRoute
  SaadanFungererDetRoute: typeof SaadanFungererDetRoute
  YdelserRoute: typeof YdelserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-os': {
      id: '/om-os'
      path: '/om-os'
      fullPath: '/om-os'
      preLoaderRoute: typeof OmOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privat-rengoering-helsingoer': {
      id: '/privat-rengoering-helsingoer'
      path: '/privat-rengoering-helsingoer'
      fullPath: '/privat-rengoering-helsingoer'
      preLoaderRoute: typeof PrivatRengoeringHelsingoerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privat-rengoering-hornbaek': {
      id: '/privat-rengoering-hornbaek'
      path: '/privat-rengoering-hornbaek'
      fullPath: '/privat-rengoering-hornbaek'
      preLoaderRoute: typeof PrivatRengoeringHornbaekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privat-rengoering-nordsjaelland': {
      id: '/privat-rengoering-nordsjaelland'
      path: '/privat-rengoering-nordsjaelland'
      fullPath: '/privat-rengoering-nordsjaelland'
      preLoaderRoute: typeof PrivatRengoeringNordsjaellandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rengoeringshjaelp-helsingoer': {
      id: '/rengoeringshjaelp-helsingoer'
      path: '/rengoeringshjaelp-helsingoer'
      fullPath: '/rengoeringshjaelp-helsingoer'
      preLoaderRoute: typeof RengoeringshjaelpHelsingoerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saadan-fungerer-det': {
      id: '/saadan-fungerer-det'
      path: '/saadan-fungerer-det'
      fullPath: '/saadan-fungerer-det'
      preLoaderRoute: typeof SaadanFungererDetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ydelser': {
      id: '/ydelser'
      path: '/ydelser'
      fullPath: '/ydelser'
      preLoaderRoute: typeof YdelserRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  OmOsRoute: OmOsRoute,
  PrivatRengoeringHelsingoerRoute: PrivatRengoeringHelsingoerRoute,
  PrivatRengoeringHornbaekRoute: PrivatRengoeringHornbaekRoute,
  PrivatRengoeringNordsjaellandRoute: PrivatRengoeringNordsjaellandRoute,
  RengoeringshjaelpHelsingoerRoute: RengoeringshjaelpHelsingoerRoute,
  SaadanFungererDetRoute: SaadanFungererDetRoute,
  YdelserRoute: YdelserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
